### ISSUE TITLE
Кент не пашет

### ISSUE THREAD

**Issue by zeromodule** [zeromodule/testgame#4]
При попытке работать с любой моделью:

[Fri Mar 20 19:10:29 2015] PHP Fatal error:  Call to a member function connection() on a non-object in /home/anton/PhpstormProjects/testgame/vendor/illuminate/database/Eloquent/Model.php on line 3141

Пример: 
$game = new Game();
$game->save();

или выборку любую.
База развернута, конфиг верный.

**Comment by excit3r** [comment]
fixed
